//! Exact native SSA failures; coordinate fields are never parsed from text.
use evm_abstract::ssa::{SsaError, SsaInvariantKind as N};
use evm_abstract_protocol::{self as api, SsaInvariantKind as P};

pub(crate) fn convert(source: SsaError) -> api::ApiError {
    let message = source.to_string();
    let details = match source {
        SsaError::Cancelled => return super::super::cancelled(),
        SsaError::IncompleteAnalysis => api::SsaFailure::Coverage,
        SsaError::Invariant(source) => api::SsaFailure::Invariant(Box::new(api::SsaInvariant {
            kind: match source.kind {
                N::CallDispatch => P::CallDispatch,
                N::DupResult => P::DupResult,
                N::RuntimeInstructionIdentity => P::RuntimeInstructionIdentity,
                N::InstructionOutsideRuntime => P::InstructionOutsideRuntime,
                N::ContiguousNames => P::ContiguousNames,
                N::ExitFrameShape => P::ExitFrameShape,
                N::SwapResult => P::SwapResult,
                N::EdgeStateMissing => P::EdgeStateMissing,
                N::BlockCount => P::BlockCount,
                N::BlockIdentity => P::BlockIdentity,
                N::CallChildFrame => P::CallChildFrame,
                N::CallSuspension => P::CallSuspension,
                N::TransitionDependencies => P::TransitionDependencies,
                N::ContinuationResultMissing => P::ContinuationResultMissing,
                N::CompletedFault => P::CompletedFault,
                N::CompletedReceiptFault => P::CompletedReceiptFault,
                N::CurrentExitMissing => P::CurrentExitMissing,
                N::DispatchResult => P::DispatchResult,
                N::DispatchReceiptResult => P::DispatchReceiptResult,
                N::DuplicateContinuationValue => P::DuplicateContinuationValue,
                N::DuplicateEffect => P::DuplicateEffect,
                N::DuplicatePartialContinuationValue => P::DuplicatePartialContinuationValue,
                N::DuplicatePartialEffect => P::DuplicatePartialEffect,
                N::DuplicatePartialValue => P::DuplicatePartialValue,
                N::DuplicateStackValue => P::DuplicateStackValue,
                N::EffectPhiCoverage => P::EffectPhiCoverage,
                N::EntryStackHeight => P::EntryStackHeight,
                N::ExecutionEffectCount => P::ExecutionEffectCount,
                N::ExecutedPcs => P::ExecutedPcs,
                N::ExitStackHeight => P::ExitStackHeight,
                N::ExtraFrameParameters => P::ExtraFrameParameters,
                N::PartialParameterOrEffect => P::PartialParameterOrEffect,
                N::FaultResult => P::FaultResult,
                N::FaultReceipt => P::FaultReceipt,
                N::FaultedPrefix => P::FaultedPrefix,
                N::FrameParameterIdentity => P::FrameParameterIdentity,
                N::FramePhiArguments => P::FramePhiArguments,
                N::InstructionEffectChain => P::InstructionEffectChain,
                N::InstructionFault => P::InstructionFault,
                N::InstructionResultArity => P::InstructionResultArity,
                N::LocalEdgeDepth => P::LocalEdgeDepth,
                N::MachineStateIdentity => P::MachineStateIdentity,
                N::CoveredEdgeParameterMissing => P::CoveredEdgeParameterMissing,
                N::EdgeArgumentMissing => P::EdgeArgumentMissing,
                N::FrameParameterMissing => P::FrameParameterMissing,
                N::PartialFrameParameterMissing => P::PartialFrameParameterMissing,
                N::BytecodeIdentity => P::BytecodeIdentity,
                N::OperandIdentity => P::OperandIdentity,
                N::ExitStackOrEffect => P::ExitStackOrEffect,
                N::PartialDupResult => P::PartialDupResult,
                N::PartialContiguousNames => P::PartialContiguousNames,
                N::FrontierCoverage => P::FrontierCoverage,
                N::PartialSwapResult => P::PartialSwapResult,
                N::PartialCallSuspension => P::PartialCallSuspension,
                N::PartialTransitionDependencies => P::PartialTransitionDependencies,
                N::PartialCallerMissing => P::PartialCallerMissing,
                N::PartialContinuationResultMissing => P::PartialContinuationResultMissing,
                N::DeferredEdgeCoverage => P::DeferredEdgeCoverage,
                N::PartialEdgeArguments => P::PartialEdgeArguments,
                N::PartialEffectPhase => P::PartialEffectPhase,
                N::PartialEffectPhiCoverage => P::PartialEffectPhiCoverage,
                N::PartialExitFrameShape => P::PartialExitFrameShape,
                N::PartialInstructionCount => P::PartialInstructionCount,
                N::PartialInstructionEffectChain => P::PartialInstructionEffectChain,
                N::PartialInstructionOutsideRuntime => P::PartialInstructionOutsideRuntime,
                N::PartialInstructionArity => P::PartialInstructionArity,
                N::PartialOperandIdentity => P::PartialOperandIdentity,
                N::PartialLocalEdgeDepth => P::PartialLocalEdgeDepth,
                N::PartialExitStackOrEffect => P::PartialExitStackOrEffect,
                N::PartialParameterIdentity => P::PartialParameterIdentity,
                N::PartialInstructionIdentity => P::PartialInstructionIdentity,
                N::PartialPhiCoverage => P::PartialPhiCoverage,
                N::PartialPhiArguments => P::PartialPhiArguments,
                N::UnfinishedPrefix => P::UnfinishedPrefix,
                N::ReceiptPcCount => P::ReceiptPcCount,
                N::ReceiptPrefix => P::ReceiptPrefix,
                N::ReceiptOutsideRuntime => P::ReceiptOutsideRuntime,
                N::PartialReturnDepth => P::PartialReturnDepth,
                N::PartialReturnCallerMissing => P::PartialReturnCallerMissing,
                N::RootReturn => P::RootReturn,
                N::PartialActiveFrameMissing => P::PartialActiveFrameMissing,
                N::PartialFrameMissing => P::PartialFrameMissing,
                N::PartialStateIdentity => P::PartialStateIdentity,
                N::PartialStatusOrBlockCount => P::PartialStatusOrBlockCount,
                N::PartialTransitionOrder => P::PartialTransitionOrder,
                N::PartialFrameIdentity => P::PartialFrameIdentity,
                N::PartialTransitionKind => P::PartialTransitionKind,
                N::PartialDestinationArguments => P::PartialDestinationArguments,
                N::PendingResult => P::PendingResult,
                N::PendingOperands => P::PendingOperands,
                N::PhiOutgoingSlot => P::PhiOutgoingSlot,
                N::PhiPredecessorCoverage => P::PhiPredecessorCoverage,
                N::PhiSlotIdentity => P::PhiSlotIdentity,
                N::ReturnDepth => P::ReturnDepth,
                N::ReturnCallerMissing => P::ReturnCallerMissing,
                N::ReturnChildFrame => P::ReturnChildFrame,
                N::ReturnWithoutCaller => P::ReturnWithoutCaller,
                N::PartialSameDepthReturn => P::PartialSameDepthReturn,
                N::SameDepthReturn => P::SameDepthReturn,
                N::UnexecutedBody => P::UnexecutedBody,
                N::StartedResult => P::StartedResult,
                N::ActiveFrameMissing => P::ActiveFrameMissing,
                N::FrameMissing => P::FrameMissing,
                N::TransitionMissing => P::TransitionMissing,
                N::FrameIdentity => P::FrameIdentity,
                N::TransitionIdentity => P::TransitionIdentity,
                N::TransitionArguments => P::TransitionArguments,
                N::DestinationArguments => P::DestinationArguments,
                N::UnreachableBlock => P::UnreachableBlock,
                N::UnsupportedTransition => P::UnsupportedTransition,
                N::ContiguousValues => P::ContiguousValues,
                N::ValuesWithoutBlocks => P::ValuesWithoutBlocks,
                N::WorldGraphSize => P::WorldGraphSize,
                N::DuplicateDefinition => P::DuplicateDefinition,
                N::UndefinedValue => P::UndefinedValue,
                N::UseBeforeDefinition => P::UseBeforeDefinition,
                N::NonDominatingDefinition => P::NonDominatingDefinition,
                N::EdgeStackHeight => P::EdgeStackHeight,
            },
            state: source.state,
            edge: source.edge,
            pc: source.pc,
            frame: source.frame,
            slot: source.slot,
            value: source.value,
            effect: source.effect,
            source_state: source.source_state,
            target_state: source.target_state,
            expected: source.expected,
            observed: source.observed,
        })),
    };
    api::ApiError {
        code: api::ApiErrorCode::Internal,
        message,
        details: api::ErrorDetails::Ssa(details),
    }
}
